apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-disability-benefit
nameSuffix: -staging
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: staging 
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-disability-benefit
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: staging 
      app.kubernetes.io/tier: nonprod
resources:
  - ../../base/cdb-estimator-frontend/
  - ./external-secrets.yaml
  - ./ingresses.yaml
patches:
  - path: ./patches/deployments.yaml
configMapGenerator:
  - name: cdb-estimator-frontend
    behavior: merge
    envs:
      - ./configs/cdb-estimator-frontend/config.conf
