apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdb-estimator-frontend
  annotations:
    secret.reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: cdb-estimator-frontend
  template:
    spec:
      containers:
        - name: cdb-estimator-frontend
          image: dtsrhpprodscedspokeacr.azurecr.io/canada-disability-benefit/cdb-estimator-frontend:1.0.0
          # since we are using external secrets operator
          # we must manually attach the generated secret
          envFrom:
            - configMapRef:
                name: cdb-estimator-frontend-prod
            - secretRef:
                name: cdb-estimator-frontend-prod
