apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef: { key: cdb-estimator/shared, property: REDIS_PASSWORD }
