#
# This overlay file is intended for deployment of shared resources across all non-production environments.
# Resources defined here will be available in all pseudo-environments (e.g., dev, staging, etc.) within the non-production namespace.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-disability-benefit
nameSuffix: -shared
labels:
  - pairs:
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: shared
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: canada-disability-benefit
      app.kubernetes.io/tier: nonprod
  - includeSelectors: true
    pairs:
      # Must have at least one unique label per environment to ensure selectors are applied correctly
      app.kubernetes.io/instance: shared
resources:
  - ../../base/redis/
  - ../../base/reloader/
  - ./external-secrets.yaml
patches:
  - path: ./patches/stateful-sets.yaml
configMapGenerator:
  - behavior: merge
    files:
      - ./configs/redis/replica.conf
      - ./configs/redis/sentinel.conf
    name: redis
