apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdb-estimator-frontend
  labels:
    app.kubernetes.io/name: cdb-estimator-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cdb-estimator-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
